考察中
ushiken3/eshop-vanilla pull request #2
Opened 2022-12-05 13:25 UTC by ushiken3

2022-12-09 09:33 UTC, yoannes requested changes
構造体を作り終えて、何か手伝えることはありますか？
Can you finish creating the structure? is there something I can help with?

これからは、あなたが練習問題を作ってみることが大切で、私たちは通話中に修正します。
It's important from now on that you try to make the exercises and we correct during our calls, it will be good for you to practice and for us to see how you are doing.

2022-12-09 09:33 UTC, yoannes commented on src/assets/controllers.js
> +    App.controllers.createFooter()
ここでは、すべての関数がAppの外側で実行されていることがわかります。これは間違っています。前に見たように、全てはAppというオブジェクトの中にあるべきです。

Here if you see, all the functions are being executed outside the App. This is wrong, like we saw it before, everything should be within the object App.

```js
const App = {
  // Koko ha inside
}

// Koko ha outside
```
```js
App.controllers = {
  // Koko ha inside
}

// Koko ha outside
```

2022-12-09 14:54 UTC, ushiken3 commented on src/assets/controllers.js
> +    App.controllers.createFooter()
ありがとうございます。さらに編集していきます。

2022-12-11 16:19 UTC, ushiken3 commented on src/assets/controllers.js
> +    App.controllers.createFooter()
手直ししてみました。ちゃんとアップロードできていますでしょうか。。。

2022-12-12 07:53 UTC, yoannes commented
Ushibaさん、こんにちは。
Ushiba-san, Helloo.

あなたのコードをチェックしていたら、`assets`フォルダの中に`index.html`を移動しているのが見えました。それは良いアイデアではないと思います。`index.html`はルートフォルダに置いておくべきです。それが標準的な方法です。 
I was checking your code and saw that you moved the `index.html` inside `assets` folder. I think that's not a good idea. You should keep the `index.html` in the root folder. That's the standard way of doing it.

ファイルをインポートするときにエラーが発生したのでしょう。インポートするときは、ファイル名の前に `./` を付ける必要があることを思い出してください。
You probably had error when importing the files, remember to import you need to use the `./` before the file name, so the browser can know where to look for the file.

```text
src
 ┣ assets
 ┃ ┣ controllers.js
 ┃ ┣ css.css
 ┃ ┣ elements.js
 ┃ ┣ events.js
 ┃ ┣ js.js
 ┃ ┣ state.js
 ┃ ┗ translate.html
 ┗ index.html
```

[More Information](https://developer.mozilla.org/ja/docs/Learn/Getting_started_with_the_web/Dealing_with_files)

2022-12-12 11:32 UTC, ushiken3 commented
ありがとうございます。いどうしてみましたが ./ をつけようとするとファイル名が無効と言われてしまいます。

2022-12-12 12:07 UTC, komurananami commented
> いどうしてみましたが ./ をつけようとするとファイル名が無効と言われてしまいます。

おそらくパスが間違っているのだと思います。
パスの書き方が正しいか確認をしてみてください。

ちなみに"./"は`src`の階層を指すので、以下のファイル構造のassetsを指定したい場合は`./assets`と書きます。
```
src
 ┣ assets
 ```

2022-12-12 12:14 UTC, merged